Vision Document
fga-eps-mds/2020.1-Grupo2-wiki pull request #10
Opened 2020-08-26 19:43 UTC by rafaelmakaha

# Description

This Pull Request resolves: #4 by adding the Vision Document file.

2020-08-28 17:22 UTC, rafaelmakaha commented
O documento está muito bom! Parabéns!

Apenas alteraria o texto em:
![image](https://user-images.githubusercontent.com/20361663/91595463-f5889c80-e939-11ea-8840-8b5d20166be4.png)

2020-08-28 17:28 UTC, senaarth commented
> O documento está muito bom! Parabéns!
> 
> Apenas alteraria o texto em:
> ![image](https://user-images.githubusercontent.com/20361663/91595463-f5889c80-e939-11ea-8840-8b5d20166be4.png)

O que você acha da seguinte substituição:

| Dificuldade na identificação de espécies. | Confusão para manutenção/cuidado para com espécime. | Mecanismos de identificação visual para substituir a necessidade de um profissional que saiba informar nome da espécie |

2020-09-01 21:32 UTC, joaovitorml requested changes
> 
> 
> > O documento está muito bom! Parabéns!
> > Apenas alteraria o texto em:
> > ![image](https://user-images.githubusercontent.com/20361663/91595463-f5889c80-e939-11ea-8840-8b5d20166be4.png)
> 
> O que você acha da seguinte substituição:
> 
> | Dificuldade na identificação de espécies. | Confusão para manutenção/cuidado para com espécime. | Mecanismos de identificação visual para substituir a necessidade de um profissional que saiba informar nome da espécie |

- [x] Ao invés de "Confusão para manutenção" eu acho que fica melhor "Problemas na manutenção";
- [x] Além disso, na tabela do tópico 1.4, eu trocaria "Esquecimento de cuidados" por "Falta de cuidado";
- [x] A branch está apresentando conflitos (no arquivo mkdocs.yml) com a develop que devem ser resolvidos.

2020-09-02 23:25 UTC, joaovitorml approved these changes

2020-09-02 23:49 UTC, merged