Created document and added topic 1
fga-eps-mds/2020.1-Grupo2-wiki pull request #77
Opened 2020-10-03 22:05 UTC by faco400

2020-10-04 20:03 UTC, faco400 commented
Quando puderem. Por favor verifiquem esse PR. Creio que está pronto.

2020-10-04 21:56 UTC, guilhermedelyra requested changes
Embora eu ache este style guide valido, acredito que uma abordagem mais interessante seria que este documento apenas explicasse por qual razão algum guia de estilo foi escolhido (por exemplo: o da [AirBnB](https://github.com/airbnb/javascript), da [Google](https://google.github.io/styleguide/jsguide.html) etc), como este foi adequado ao nosso projeto (acaso alguma configuração tenha sido desativada [por exemplo: desabilitar 'template_strings' no linter do airbnb) e, finalmente, um link redirecionando ao proprio guia de estilo

2020-10-04 21:56 UTC, guilhermedelyra commented on docs/document_style_guide/Nodejs_style_guide.md
> +<!-- ### Use UPPERCASE for Constants
isso aqui deveria aparecer :D

2020-10-04 21:56 UTC, guilhermedelyra commented on docs/document_style_guide/Nodejs_style_guide.md
> +*Right:*
traduzir pra pt-br :P

2020-10-04 21:56 UTC, guilhermedelyra commented on docs/document_style_guide/Nodejs_style_guide.md
> +<!-- ### Use multi-line ternary operator
essa parte tbm é util hehe

2020-10-04 21:56 UTC, guilhermedelyra commented on docs/document_style_guide/Nodejs_style_guide.md
> +Utilize fechamentos, mas não aninhe-os. Caso contrário o seu codigo era se tornar uma bagunça.
seria interessante citar sobre as abordagens pra se evitar callback hells =D
boa referencia: http://callbackhell.com

2020-10-05 21:02 UTC, faco400 commented
Fiz as mudanças que você falou Guilherme.

2020-10-08 18:07 UTC, guilhermedelyra requested changes

2020-10-08 18:07 UTC, guilhermedelyra commented on docs/document_style_guide/Nodejs_style_guide.md
> +para nós pois ao contrário do guia utilizado como base. O guia disponibilizado no repositório Airbnb tem recebido suporte contínuo, inclusive durante o ano de criação deste documento. Por esse motivo
acredito que pra esse documento basta referenciar o guia de estilo do Airbnb e, como material complementar, citar este documento aqui presente (ou o proprio guia do @felixge)

pois o uso do guia de estilos do AirBnb será 'mandatorio' [já que sera avaliado pelo linter se o codigo produzido está de acordo ou não]

2020-10-08 19:00 UTC, faco400 commented on docs/document_style_guide/Nodejs_style_guide.md
> +para nós pois ao contrário do guia utilizado como base. O guia disponibilizado no repositório Airbnb tem recebido suporte contínuo, inclusive durante o ano de criação deste documento. Por esse motivo
Pronto! Creio que agora está condizente com o que você disse

2020-10-14 15:20 UTC, rafaelmakaha requested changes
O guia de estilo do NodeJS está muito bom!

Mas ainda falta o do React Native

2020-10-14 18:15 UTC, faco400 commented
Pronto. Criei um documento falando do Guia do React Native.

2020-10-15 15:43 UTC, guilhermedelyra commented
Ótimo! Aprovando

2020-10-15 15:44 UTC, guilhermedelyra approved these changes
ótimo!

2020-10-15 15:44 UTC, merged